a = input('Digite algo: ')
print('O tipo primitivo deste valor é uma: ', type(a))
print('Isto é um digito?', a.isdigit())
print('Isto é um alfanumérico?', a.isalnum())
print('Isto é um alfabético?', a.isalpha())
print('Isto é um ascii?', a.isascii())
print('Isto é um decimal?', a.isdecimal())
print('Isto é um identificador?', a.isidentifier())
print('Isto é um minúsculo?', a.islower())
print('Isto é um numérico?', a.isnumeric())
print('Isto é um printable?', a.isprintable())
print('Só tem espaço?', a.isspace())
print('Isto está Captalizado?', a.istitle())
print('Isto é um maiúsculo? {}' .format(a.isupper()))