comp = float(input('Digite o comprimento em metros: '))
print('Temos então:')
print('- {} metro(s)'.format(comp))
print('- {} centímetro(s)'.format(comp*10**2))
print('- {} milímetro(s)'.format(comp*10**3))