a = input('Digite algo: ')
print(type(a))
print('Isto é um digito?', a.isdigit())
print('Isto é um alfanumérico?', a.isalnum())
print('Isto é um alfabético?', a.isalpha())
print('Isto é um ascii?', a.isascii())
print('Isto é um decimal?', a.isdecimal())
print('Isto é um identificador?', a.isidentifier())
print('Isto é um minúsculo?', a.islower())
print('Isto é um numérico?', a.isnumeric())
print('Isto é um printable?', a.isprintable())
print('Isto é um espaço?', a.isspace())
print('Isto é um título?', a.istitle())
print('Isto é um maiúsculo?', a.isupper())